services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch_data:/usr/share/elasticsearch/data
    depends_on:
      - init-elasticsearch

  init-elasticsearch:
    image: busybox
    command: sh -c "mkdir -p /usr/share/elasticsearch/data && chown -R 1000:1000 /usr/share/elasticsearch/data && chmod -R 755 /usr/share/elasticsearch/data"
    volumes:
      - ./data/elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=elastic_db
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.0
    volumes:
      - ./logstash/pipeline/logstash_products.conf:/usr/share/logstash/pipeline/logstash_products.conf:ro
      - ./logstash/pipeline/logstash_users.conf:/usr/share/logstash/pipeline/logstash_users.conf:ro
      - ./logstash/pipeline/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/lib/mysql-connector-java-8.0.30.jar:/usr/share/logstash/mysql-connector-java-8.0.30.jar:ro
    depends_on:
      - elasticsearch
      - mysql
volumes:
  elasticsearch_data:
  mysql_data:
